
(message "my age is %d" 16)

(hl-line-highlight)

(message (rx "my age is %d") 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
(message "my age is %d" 16)
